// components/sections/OverviewSection.tsx
import SectionWrapper from '../../common/SectionWrapper';
import SectionTitle from '../../common/SectionTitle';
import Container from '../../common/Container';

const MacBookContainer = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="relative max-w-4xl mx-auto">
      {/* MacBook Top Bar with Dots */}
      <div className="absolute top-4 left-4 flex gap-2 z-10">
        <div className="w-3 h-3 rounded-full bg-red-500" />
        <div className="w-3 h-3 rounded-full bg-yellow-500" />
        <div className="w-3 h-3 rounded-full bg-green-500" />
      </div>
      
      <Container className="p-0 overflow-hidden">
        <div className="px-6 py-8 md:px-8 md:py-10">
          {children}
        </div>
      </Container>
    </div>
  );
};

const OverviewSection = () => {
  return (
    <SectionWrapper>
      <SectionTitle>Overview</SectionTitle>
      
      <MacBookContainer>
        <div className="font-mono text-sm md:text-base">
          <pre className="text-secondary">
            <code>
              <span className="text-accent">// architext.config.js</span>{'\n'}
              <span className="text-accent">&#123;</span>{'\n'}
              <span className="ml-4">  architecture: </span>
              <span className="text-green-500">'feature-first'</span>,{'\n'}
              <span className="ml-4">  rules: [</span>{'\n'}
              <span className="ml-8">    &#123;</span>{'\n'}
              <span className="ml-12">      name: </span>
              <span className="text-green-500">'layer-boundaries'</span>,{'\n'}
              <span className="ml-12">      enforcement: </span>
              <span className="text-blue-400">'strict'</span>{'\n'}
              <span className="ml-8">    &#125;</span>{'\n'}
              <span className="ml-4">  ]</span>{'\n'}
              <span className="text-accent">&#125;</span>{'\n\n'}
              <span className="text-accent">// Auto-generated by Architext</span>{'\n'}
              <span className="text-accent">// Detected 3 layer violations</span>{'\n'}
              <span className="text-red-400">⚠  src/utils/feature.ts → Should be in features/</span>{'\n'}
              <span className="text-red-400">⚠  src/components/api.ts → Should be in core/</span>
            </code>
          </pre>
        </div>
      </MacBookContainer>
    </SectionWrapper>
  );
};

export default OverviewSection;