# 1. An official Node.js runtime as a parent image
FROM node:22.15-alpine3.21

# 2. Set the working directory inside the container
WORKDIR /app

# 3. Copy package.json and package-lock.json first
# (this allows Docker to cache npm install unless these files change)
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Copy the rest of the application code
COPY . .

# 6. Copy the shell script into the container (make sure the script has execution permissions)
COPY ./shell.sh /app/shell.sh
RUN chmod +x /app/shell.sh

# 7. Run the setup script to handle migrations, seeding, etc.
RUN ./shell.sh

# 8. For production
RUN npm run build

# 9. Expose the port the app runs on
EXPOSE 3000

# 10. Command to run the app
CMD ["npm", "start"]
